SS18 release?
Roboy/roboy_memory pull request #50
Opened 2018-09-17 16:23 UTC by missxa

2018-09-18 09:16 UTC, Aevyz requested changes
Please pull #51 into here, changes version, removes a GitIgnore line and changes the neo4j version, due to a bug in 3.4 docker installation refusing to grant permission to logging folder (3.0 works out of the box)

Will update once I find a solution that does not involve giving everyone on the computer sudo access to that folder...

2018-09-18 20:56 UTC, missxa commented
@aevyz we're good now? let's merge?

2018-09-19 10:34 UTC, Aevyz approved these changes

2018-09-19 10:35 UTC, Aevyz commented
@missxa I'm happy

2018-09-20 14:09 UTC, merged